compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
main = "src/main.ts"
name = "zuko-backend"

[vars]
OAK_NATIONAL_ACADEMY_HTTP_URL = "https://open-api.thenational.academy/api/v0/"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
